version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ~/pg/pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "54321:5432"
  flask:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: flask
    volumes:
      - ~/migrations:/app/migrations
      - ~/uploads:/app/app/static/uploads
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - flask
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./certbot/www:/var/www/certbot"
      - "./certbot/conf:/etc/letsencrypt"